name: Dump Entities from Baserow

on:
  schedule:
    - cron: "23 23 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: enrich the data
        run: python enrich_data.py
      - name: dump the data
        run: |
          python dump_data.py
      - name: join the data
        run: |
          python join_tables.py
      - name: merge certain districts
        run: |
          python merge_districts.py
      - name: filter upper administrative unit lists
        run: |
          python unique_upper_admins.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data update from Baserow
